### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by MoshDev** [carlenlund/lime-remote#3]
It would be cool if this supports Mac OS

**Comment by carlenlund** [comment]
For sure! I don't have access to a Mac currently, but do you get any particular errors when running the following commands?

1. `npm install`
2. `npm run rebuild`
3. `npm run machine`

In theory this should work on Mac since I'm using cross-platform libraries.

**Comment by carlenlund** [comment]
I'm closing this issue for now. Please let me know if the issue remains!
